# Generated by Django 5.1.5 on 2025-02-04 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_account_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('account_username', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('training_completed', models.BooleanField()),
                ('is_analyst', models.CharField(max_length=1)),
                ('is_administrator', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=64)),
                ('product_stage', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=4)),
                ('time_received', models.DateTimeField()),
                ('sample_type', models.CharField(max_length=1)),
                ('storage_conditions', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('location_type', models.CharField(blank=True, max_length=64, null=True)),
                ('room_number', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('sop_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('sop_name', models.CharField(max_length=16)),
                ('version_number', models.DecimalField(decimal_places=1, max_digits=3)),
                ('effective_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.useraccount')),
                ('is_supervisor', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.useraccount')),
                ('access_level', models.DecimalField(decimal_places=0, max_digits=1)),
                ('analyst_supervisor', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.sample')),
                ('product_lot_number', models.DecimalField(decimal_places=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='InProcess',
            fields=[
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.sample')),
                ('time_sampled', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stability',
            fields=[
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.sample')),
                ('stability_conditions', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=64)),
                ('min_use_range', models.DecimalField(decimal_places=6, max_digits=10)),
                ('max_use_range', models.DecimalField(decimal_places=6, max_digits=10)),
                ('in_use', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sop')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sop'),
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('reagent_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('reagent_name', models.CharField(max_length=255)),
                ('cas_number', models.CharField(max_length=12)),
                ('lot_number', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('manufacturing_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sop')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('maintenance_log_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('service_description', models.CharField(max_length=4000)),
                ('service_interval', models.CharField(max_length=64)),
                ('next_service_date', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipment')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sop')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('min_acceptable_result', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('max_acceptable_result', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sop')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTestLink',
            fields=[
                ('sample_test_link_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('testing_analyst', models.CharField(max_length=64)),
                ('reviewing_analyst', models.CharField(max_length=64)),
                ('test_result', models.DecimalField(decimal_places=6, max_digits=10)),
                ('deadline', models.DateTimeField()),
                ('pass_or_fail', models.BooleanField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestEquipmentLink',
            fields=[
                ('test_equipment_link_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipment')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestReagentLink',
            fields=[
                ('test_reagent_link_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('volume_used', models.DecimalField(decimal_places=6, max_digits=10)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reagent')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
        ),
        migrations.CreateModel(
            name='UserReagentAction',
            fields=[
                ('user_reagent_action_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('reagent_manager', models.CharField(max_length=64)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reagent')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserSampleAction',
            fields=[
                ('user_sample_action_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('receiving_analyst', models.CharField(max_length=64)),
                ('aliquoting_analyst', models.CharField(blank=True, max_length=64, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sample')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserSOPAction',
            fields=[
                ('user_sop_action_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('qa_author', models.CharField(max_length=64)),
                ('qa_reviewer', models.CharField(max_length=64)),
                ('qa_approver', models.CharField(max_length=64)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sop')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='VersionChange',
            fields=[
                ('version_change_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('old_version_number', models.DecimalField(decimal_places=1, max_digits=3)),
                ('new_version_number', models.DecimalField(decimal_places=1, max_digits=3)),
                ('old_effective_date', models.DateField()),
                ('new_effective_date', models.DateField()),
                ('change_date', models.DateField()),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sop')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('warehouse_technician', models.CharField(max_length=64)),
                ('warehouse_facility', models.CharField(max_length=64)),
                ('warehouse_company', models.CharField(max_length=64)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sop')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
        migrations.CreateModel(
            name='WarehouseClientLink',
            fields=[
                ('warehouse_client_link_id', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('quantity_shipped', models.DecimalField(decimal_places=0, max_digits=4)),
                ('delivery_service', models.CharField(max_length=64)),
                ('shipping_time', models.DateTimeField()),
                ('delivery_time', models.DateTimeField()),
                ('acceptable_delivery', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouse')),
            ],
        ),
    ]
