#!/usr/bin/env python3
"""
This script serves as the command‑line utility for administrative tasks.  It mirrors
the default ``manage.py`` generated by Django's ``startproject`` command.  Running
this file with various commands (e.g. ``runserver``, ``migrate``, ``createsuperuser``)
invokes the appropriate management function from Django's core.

Because this repository ships without Django preinstalled, you must install
``django`` and the other dependencies listed in ``backend/requirements.txt``
before this script can be executed.  See the README in the ``backend``
directory for setup instructions.
"""

import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "lims_project.settings")
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()